# Contents
1. Question 1: What's the version of NumPy that you installed?
2. Question 2: What's the version of Pandas?
3. Question 3: What's the average price of BMW cars in the dataset?
4. Question 4: Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?
5. Question 5: 
  *   Calculate the average "Engine HP" in the dataset.
  *   Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
  *   Now, calculate the average of "Engine HP" again.
  *   Has it changed?
6. Question 6:
  * Select all the "Rolls-Royce" cars from the dataset.
  * Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
  * Drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
  * Get the underlying NumPy array. Let's call it X.
  * Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
  * Invert XTX.
  * What's the sum of all the elements of the result?
7. Question 7:
  * Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
  * Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
  * What's the value of the first element of w?.





In [1]:
# Import packages
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
# Getting the data
link = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'

car_price = pd.read_csv(link)

In [5]:
car_price.head()

Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]

# Question 1: What's the version of NumPy that you installed?

In [2]:
print("My numpy version is {}".format(np.__version__))

My numpy version is 1.19.5


# Question 2: What's the version of Pandas?

In [3]:
print("My pandas version is {}".format(pd.__version__))

My pandas version is 1.1.5


# Question 3: What's the average price of BMW cars in the dataset?

In [55]:
# Subset BMW cars 
BMW = car_price[car_price['Make'] == 'BMW']

# Print average price
print("The average price of BMW cars is $ {0:.2f}".format(BMW['MSRP'].mean()))

The average price of BMW cars is $ 61546.76


# Question 4: Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [56]:
# Subset after year 2015
after_2015 = car_price[car_price['Year'] >= 2015]

print("There are {} missing values in Engine HP".format(after_2015['Engine HP'].isna().sum()))

There are 51 missing values in Engine HP


# Question 5

## Calculate the average "Engine HP" in the dataset

In [57]:
mean_engine_HP = after_2015['Engine HP'].mean()
print("The average of Engine HP is {}".format(mean_engine_HP))

The average of Engine HP is 272.98771870794076


## Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.

In [58]:
after_2015['Engine HP'] = after_2015['Engine HP'].fillna(mean_engine_HP)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [60]:
print(after_2015['Engine HP'].isna().sum())

0


## Now, calculate the average of "Engine HP" again.

In [61]:
new_mean_HP = after_2015['Engine HP'].mean()
print("The average of Engine HP after filling NA values is {}".format(new_mean))

The average of Engine HP after filling NA values is 272.98771870794116


## Has it changed?

In [62]:
new_mean_HP == mean_engine_HP

False

The average is still the same eventhough we have filled the missing values with previous means of Engine HP

# Question 6

## Select all the "Rolls-Royce" cars from the dataset.

In [36]:
rolls_royce = car_price[car_price['Make'] == 'Rolls-Royce']

## Select only columns "Engine HP", "Engine Cylinders", "highway MPG".

In [37]:
rolls_royce = rolls_royce[['Engine HP','Engine Cylinders','highway MPG']]

In [39]:
rolls_royce

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

## Drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).

In [40]:
rolls_royce.drop_duplicates(inplace = True)

In [41]:
rolls_royce

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

## Get the underlying NumPy array. Let's call it X.

In [42]:
X = np.array(rolls_royce)

In [43]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

## Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [45]:
XT = np.transpose(X)
XTX = np.matmul(XT, X)
print(XTX)

[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]


## Invert XTX

In [47]:
XTX_inverse = np.linalg.inv(XTX)
print(XTX_inverse)

[[ 5.17815728e-05  9.06587044e-04 -1.92984188e-03]
 [ 9.06587044e-04  1.05723058e-01 -8.87084092e-02]
 [-1.92984188e-03 -8.87084092e-02  1.05900809e-01]]


## What's the sum of all the elements of the result?

In [49]:
print("The sum of all elements of the inverse XTX is {}".format(np.sum(XTX_inverse)))

The sum of all elements of the inverse XTX is 0.032212320677486125


# Question 7

## Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].

In [50]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

## Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [51]:
w = np.matmul(np.matmul(XTX_inverse, XT), y)

In [52]:
print(w)

[ 0.19989598 31.02612262 31.65378877]


## What's the value of the first element of w?

In [54]:
print("The value of the first element of w is {}".format(w[0]))

The value of the first element of w is 0.19989598183188978
